project_id = "wcnomdrzqbnaaleaqfsh"

[functions.google-drive-auth]
verify_jwt = false

[functions.google-drive-callback]
verify_jwt = false

[functions.google-drive-backup]
verify_jwt = false

[functions.google-drive-restore]
verify_jwt = false

[functions.rate-limit]
verify_jwt = false
